"use strict";

window.GaluchatMapDatasets = [
  {
    id: "jp-2024-mlit-go-jp-n03-adm",
    title: ["日本の行政区域（2024）", "Japan administrative areas (2024)"],
    description: ["2024年版の都道府県・市区町村の境界を表示します。", "Explore 2024 prefecture and municipality boundaries."],
    area: ["対象: 日本の都道府県・市区町村", "Coverage: Japan's prefectures and municipalities"],
    center: { lon: 140.0267, lat: 35.6810 },
    initialLevelIndex: 6,
    credit: ["国土交通省「国土数値情報（行政区域データ）2024年版」をGaluchat用に加工して作成。", "Adapted for Galuchat from National Land Numerical Information (Administrative Area Data, 2024), Ministry of Land, Infrastructure, Transport and Tourism."],
    license: ["CC BY 4.0", "CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"],
    approval: ["測量法に基づく国土地理院長承認（使用）R 8JHs 319", "GSI approval for use: R 8JHs 319"],
    samples: [["津田沼", 140.0206, 35.6911], ["東京", 139.7671, 35.6812], ["京都", 135.7588, 34.9858]],
  },
  {
    id: "jp-2025-mlit-go-jp-n03-adm",
    title: ["日本の行政区域（2025）", "Japan administrative areas (2025)"],
    description: ["2025年版の都道府県・市区町村の境界を表示します。", "Explore 2025 prefecture and municipality boundaries."],
    area: ["対象: 日本の都道府県・市区町村", "Coverage: Japan's prefectures and municipalities"],
    center: { lon: 140.0267, lat: 35.6810 },
    initialLevelIndex: 6,
    credit: ["国土交通省「国土数値情報（行政区域データ）2025年版」をGaluchat用に加工して作成。", "Adapted for Galuchat from National Land Numerical Information (Administrative Area Data, 2025), Ministry of Land, Infrastructure, Transport and Tourism."],
    license: ["CC BY 4.0", "CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"],
    approval: ["測量法に基づく国土地理院長承認（使用）R 8JHs 319", "GSI approval for use: R 8JHs 319"],
    samples: [["津田沼", 140.0206, 35.6911], ["東京", 139.7671, 35.6812], ["京都", 135.7588, 34.9858]],
  },
  {
    id: "jp-2026-mlit-go-jp-n03-adm",
    title: ["日本の行政区域（2026）", "Japan administrative areas (2026)"],
    description: ["都道府県・市区町村の境界を表示します。", "Explore prefecture and municipality boundaries."],
    area: ["対象: 日本の都道府県・市区町村", "Coverage: Japan's prefectures and municipalities"],
    center: { lon: 140.0267, lat: 35.6810 },
    initialLevelIndex: 6,
    credit: ["国土交通省「国土数値情報（行政区域データ）」をGaluchat用に加工して作成。", "Adapted for Galuchat from National Land Numerical Information (Administrative Area Data), Ministry of Land, Infrastructure, Transport and Tourism."],
    license: ["CC BY 4.0", "CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"],
    approval: ["測量法に基づく国土地理院長承認（使用）R 8JHs 319", "GSI approval for use: R 8JHs 319"],
    samples: [["津田沼", 140.0206, 35.6911], ["東京", 139.7671, 35.6812], ["京都", 135.7588, 34.9858]],
  },
  {
    id: "jp-2020-e-stat-go-jp-a002005212020-stat-small-area",
    title: ["日本の町丁・字等境界（2020）", "Japanese town-block and small-area boundaries (2020)"],
    description: ["町丁・字等の小地域を表示します。", "Explore town blocks and census small areas."],
    area: ["対象: 日本の町丁・字等境界", "Coverage: Japan's town blocks and census small areas"],
    center: { lon: 140.0206, lat: 35.6911 },
    initialLevelIndex: 2,
    padding: 96,
    credit: ["総務省統計局・e-Stat「令和2年国勢調査 町丁・字等境界データ」をGaluchat用に加工して作成。", "Adapted for Galuchat from 2020 Population Census town-block and small-area boundaries, Statistics Bureau of Japan and e-Stat."],
    license: ["e-Stat利用規約", "e-Stat terms of use", "https://www.e-stat.go.jp/terms-of-use"],
    samples: [["津田沼", 140.0206, 35.6911], ["東京", 139.7671, 35.6812], ["京都", 135.7588, 34.9858]],
  },
  {
    id: "jp-2026-nyatla-jp-estat-coastline",
    title: ["日本の海岸線反映区域（2026・2020）", "Japan coastline-adjusted areas (2026 and 2020)"],
    description: ["2026年版の行政区域と2020年の町丁・字等境界を統合した区域を表示します。", "Explore areas combining 2026 administrative boundaries with 2020 census small-area boundaries."],
    area: ["対象: 日本の海岸線反映区域", "Coverage: Japan's coastline-adjusted areas"],
    center: { lon: 140.0206, lat: 35.6911 },
    initialLevelIndex: 2,
    padding: 96,
    credit: ["国土交通省「国土数値情報（行政区域データ）」と総務省統計局・e-Stat「令和2年国勢調査 町丁・字等境界データ」をGaluchat用に加工・統合。", "Adapted and combined for Galuchat from National Land Numerical Information administrative areas and 2020 Population Census small-area boundaries (Statistics Bureau of Japan and e-Stat)."],
    license: ["国土数値情報の利用規約", "National Land Numerical Information terms", "https://nlftp.mlit.go.jp/ksj/other/agreement.html"],
    caveat: ["e-Statの利用条件も適用されます。承認表示の適用範囲には原パッケージのNOTICEに未確認事項があります。", "e-Stat terms also apply. The source package NOTICE flags an unresolved question about the approval statement's scope."],
    samples: [["津田沼", 140.0206, 35.6911], ["東京", 139.7671, 35.6812], ["京都", 135.7588, 34.9858]],
  },
  {
    id: "tw-2026-maps-nlsc-gov-tw-village-adm",
    title: ["台湾の村里界（2026）", "Taiwan village boundaries (2026)"],
    description: ["縣市・鄉鎮市區・村里の境界を表示します。", "Explore county, district, and village boundaries."],
    area: ["対象: 台湾の村里界", "Coverage: Taiwan's village boundaries"],
    center: { lon: 121.5654, lat: 25.0330 },
    initialLevelIndex: 6,
    credit: ["內政部國土測繪中心の2026年村里界圖（2026-08-17版）をGaluchat用に加工。", "Adapted for Galuchat from the National Land Surveying and Mapping Center 2026 Village Boundary Map, 2026-08-17 edition."],
    license: ["政府資料開放授權條款－第1版", "Open Government Data License, version 1.0", "https://data.gov.tw/license"],
    samples: [["Taipei", 121.5645, 25.0339], ["Taichung", 120.6853, 24.1368], ["Kaohsiung", 120.3027, 22.6398]],
  },
  {
    id: "gb-2025-geoportal-statistics-gov-uk-lad-adm-bfc",
    title: ["英国の地方自治体地区（2025）", "UK local authority districts (2025)"],
    description: ["構成国・County・Local Authority Districtを表示します。", "Explore constituent countries, counties, and local authority districts."],
    area: ["対象: 英国のLocal Authority District", "Coverage: UK local authority districts"],
    center: { lon: -0.1276, lat: 51.5072 },
    initialLevelIndex: 6,
    credit: ["ONS Local Authority Districts (December 2025) UK BFCをGaluchat用に加工。OS data © Crown copyright and database right 2026を含みます。", "Adapted for Galuchat from ONS Local Authority Districts (December 2025) UK BFC. Contains OS data © Crown copyright and database right 2026."],
    license: ["Open Government Licence v3.0", "Open Government Licence v3.0", "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"],
    caveat: ["BFC境界は海岸線で切り取られており、法的・地籍上の境界を示すものではありません。", "BFC boundaries are clipped to the coastline and are not authoritative legal or cadastral boundaries."],
    samples: [["London", -0.1276, 51.5072], ["Edinburgh", -3.1883, 55.9533], ["Cardiff", -3.1791, 51.4816], ["Belfast", -5.9301, 54.5973]],
  },
  {
    id: "us-2025-census-gov-tl-county-adm2",
    title: ["米国のCounty境界（2025）", "U.S. county boundaries (2025)"],
    description: ["州とCounty、Parish、Boroughなどの境界を表示します。", "Explore states, counties, parishes, boroughs, and equivalents."],
    area: ["対象: 米国50州・District of ColumbiaのCounty等", "Coverage: counties and equivalents in the 50 U.S. states and District of Columbia"],
    center: { lon: -98.5795, lat: 39.8283 },
    initialLevelIndex: 6,
    credit: ["U.S. Census Bureau 2025 TIGER/Line County and Equivalent EntitiesをGaluchat用に加工。", "Adapted for Galuchat from U.S. Census Bureau 2025 TIGER/Line County and Equivalent Entities."],
    license: ["U.S. Census Bureau TIGER/Line", "U.S. Census Bureau TIGER/Line", "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2025.html"],
    caveat: ["境界は統計目的のTIGER/Line形状で、物理的な海岸線では切り取っていません。法的・地籍上の境界ではありません。", "These TIGER/Line statistical boundaries are not clipped to a physical coastline and are not authoritative legal or cadastral boundaries."],
    samples: [["New York", -74.0060, 40.7128], ["Los Angeles", -118.2437, 34.0522], ["Honolulu", -157.8583, 21.3069]],
  },
  {
    id: "us-2025-census-gov-tl-state-adm1",
    title: ["米国のState境界（2025）", "U.S. state boundaries (2025)"],
    description: ["50州とDistrict of Columbiaの境界を表示します。", "Explore boundaries of the 50 states and District of Columbia."],
    area: ["対象: 米国50州・District of Columbia", "Coverage: the 50 U.S. states and District of Columbia"],
    center: { lon: -98.5795, lat: 39.8283 },
    initialLevelIndex: 6,
    credit: ["U.S. Census Bureau 2025 TIGER/Line State and Equivalent EntitiesをGaluchat用に加工。米国国勢調査局による公認ではありません。", "Adapted for Galuchat from U.S. Census Bureau 2025 TIGER/Line State and Equivalent Entities. Not endorsed by the U.S. Census Bureau."],
    license: ["U.S. Census Bureau TIGER/Line", "U.S. Census Bureau TIGER/Line", "https://www.census.gov/geographies/mapping-files/2025/geo/tiger-line-file.html"],
    caveat: ["統計目的の境界であり、法的・地籍上の境界ではありません。", "These statistical boundaries are not authoritative legal or cadastral boundaries."],
    samples: [["New York", -74.0060, 40.7128], ["Los Angeles", -118.2437, 34.0522], ["Honolulu", -157.8583, 21.3069]],
  },
  {
    id: "ca-2021-statcan-gc-ca-csd-cbf-stat-csd",
    title: ["カナダのCensus Subdivision（2021）", "Canada census subdivisions (2021)"],
    description: ["2021年国勢調査のCensus Subdivision境界を表示します。", "Explore 2021 census subdivision boundaries."],
    area: ["対象: カナダのCensus Subdivision", "Coverage: Canada's census subdivisions"],
    center: { lon: -75.6972, lat: 45.4215 },
    initialLevelIndex: 6,
    credit: ["Statistics Canada 2021 Census Subdivision Cartographic Boundary FileをGaluchat用に加工。Open Government Licence – Canadaに基づく情報を含みます。", "Adapted for Galuchat from Statistics Canada 2021 Census Subdivision Cartographic Boundary File. Contains information licensed under the Open Government Licence – Canada."],
    license: ["Open Government Licence – Canada 2.0", "Open Government Licence – Canada 2.0", "https://open.canada.ca/en/open-government-licence-canada"],
    samples: [["Ottawa", -75.6972, 45.4215], ["Toronto", -79.3832, 43.6532], ["Vancouver", -123.1207, 49.2827]],
  },
  {
    id: "world-2024-geoboundaries-org-cgaz-adm",
    title: ["世界の行政区域（2024）", "Administrative areas worldwide (2024)"],
    description: ["国と、各地域で利用可能な最詳細の行政区域を表示します。", "Explore countries and the most detailed available administrative area in each region."],
    area: ["対象: 世界の行政区域（地域によって粒度が異なります）", "Coverage: worldwide administrative areas (detail varies by region)"],
    center: { lon: 140.0267, lat: 35.6810 },
    initialLevelIndex: 3,
    credit: ["William & Mary geoLabおよびgeoBoundariesコミュニティのgeoBoundariesをGaluchat用に加工。", "Adapted for Galuchat from geoBoundaries, produced by the William & Mary geoLab and the geoBoundaries community."],
    license: ["CC BY 4.0", "CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"],
    samples: [["Paris", 2.3522, 48.8566], ["New York", -74.0060, 40.7128], ["Tokyo", 139.6917, 35.6895], ["Sydney", 151.2093, -33.8688], ["Cape Town", 18.4241, -33.9249]],
  },
  {
    id: "au-2021-abs-gov-au-sal-stat-sal",
    title: ["オーストラリアのSuburb・Locality（2021）", "Australia suburbs and localities (2021)"],
    description: ["ASGSのSuburb・Locality区域を表示します。", "Explore ASGS suburb and locality areas."],
    area: ["対象: オーストラリアのSuburb・Locality", "Coverage: Australia's suburbs and localities"],
    center: { lon: 151.2093, lat: -33.8688 },
    initialLevelIndex: 6,
    credit: ["Australian Bureau of Statistics, ASGS Edition 3, Suburbs and Localities 2021をGaluchat用に加工。", "Adapted for Galuchat from Australian Bureau of Statistics, ASGS Edition 3, Suburbs and Localities 2021."],
    license: ["CC BY 4.0", "CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"],
    samples: [["Sydney", 151.2093, -33.8688], ["Melbourne", 144.9631, -37.8136], ["Brisbane", 153.0251, -27.4698]],
  },
  {
    id: "de-2026-gdz-bkg-bund-de-vg250-adm",
    title: ["ドイツの行政区域（2026）", "Germany administrative areas (2026)"],
    description: ["VG250の行政区域を表示します。", "Explore administrative areas from VG250."],
    area: ["対象: ドイツの行政区域", "Coverage: Germany's administrative areas"],
    center: { lon: 13.4050, lat: 52.5200 },
    initialLevelIndex: 6,
    credit: ["© BKG 2026。VG250をGaluchat用に加工。BKGによる公認ではありません。", "© BKG 2026. VG250 adapted for Galuchat. Not endorsed by BKG."],
    creditLinks: [["BKG", "https://www.bkg.bund.de"], ["Datenquellen", "https://sgx.geodatenzentrum.de/web_public/gdz/datenquellen/datenquellen_vg_nuts.pdf"]],
    license: ["dl-de/by-2-0", "dl-de/by-2-0", "https://www.govdata.de/dl-de/by-2-0"],
    samples: [["Berlin", 13.4050, 52.5200], ["Hamburg", 9.9937, 53.5511], ["Munich", 11.5820, 48.1351]],
  },
  {
    id: "fr-2026-cartes-gouv-fr-admin-express-cog-adm",
    title: ["フランスの行政区域（2026）", "France administrative areas (2026)"],
    description: ["ADMIN EXPRESS COGの行政区域を表示します。", "Explore administrative areas from ADMIN EXPRESS COG."],
    area: ["対象: フランスの行政区域", "Coverage: France's administrative areas"],
    center: { lon: 2.3522, lat: 48.8566 },
    initialLevelIndex: 6,
    credit: ["IGN ADMIN EXPRESS COG 2026をGaluchat用に加工。", "Adapted for Galuchat from IGN ADMIN EXPRESS COG 2026."],
    license: ["Licence Ouverte 2.0", "Open Licence 2.0", "https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf"],
    samples: [["Paris", 2.3522, 48.8566], ["Lyon", 4.8357, 45.7640], ["Marseille", 5.3698, 43.2965]],
  },
  {
    id: "nl-2026-cbs-nl-wijkbuurtkaart-adm",
    title: ["オランダの自治体区域（2026）", "Netherlands municipalities (2026)"],
    description: ["CBS Wijk- en Buurtkaartの自治体区域を表示します。", "Explore municipalities from the CBS Wijk- en Buurtkaart."],
    area: ["対象: 欧州側オランダの自治体区域", "Coverage: municipalities in the European Netherlands"],
    center: { lon: 4.9041, lat: 52.3676 },
    initialLevelIndex: 6,
    credit: ["CBS・Kadaster「Wijk- en Buurtkaart 2026」をGaluchat用に加工。", "Adapted for Galuchat from CBS and Kadaster, Wijk- en Buurtkaart 2026."],
    license: ["CC BY 4.0", "CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"],
    caveat: ["原典で区分された水域にも区域コードがあります。", "Source-defined water areas also have region codes."],
    samples: [["Amsterdam", 4.9041, 52.3676], ["Rotterdam", 4.4792, 51.9225], ["Utrecht", 5.1214, 52.0907]],
  },
  {
    id: "nl-2026-cbs-nl-wijkbuurtkaart-stat-buurt",
    title: ["オランダのWijk・Buurt（2026）", "Netherlands Wijk and Buurt areas (2026)"],
    description: ["CBS Wijk- en BuurtkaartのBuurt区域とWijkの名称階層を表示します。", "Explore Buurt areas and their Wijk name hierarchy from the CBS Wijk- en Buurtkaart."],
    area: ["対象: 欧州側オランダのBuurt区域", "Coverage: Buurt areas in the European Netherlands"],
    center: { lon: 4.9041, lat: 52.3676 },
    initialLevelIndex: 6,
    credit: ["CBS・Kadaster「Wijk- en Buurtkaart 2026」をGaluchat用に加工。", "Adapted for Galuchat from CBS and Kadaster, Wijk- en Buurtkaart 2026."],
    license: ["CC BY 4.0", "CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"],
    caveat: ["Wijk・Buurtは統計・地域区分です。原典で区分された水域にも区域コードがあります。", "Wijk and Buurt are statistical and local areas. Source-defined water areas also have region codes."],
    samples: [["Amsterdam", 4.9041, 52.3676], ["Rotterdam", 4.4792, 51.9225], ["Utrecht", 5.1214, 52.0907]],
  },
];
